name: Znas Upload
description: |
  A GitHub Action that uploads a folder or file to Znas using Puppeteer via Docker.

inputs:
  upload_url:
    description: The URL to upload files to
    required: true
  upload_path:
    description: The path of the folder or file to upload
    required: true
  upload_name:
    description:
      The optional name for the uploaded zip file or file (without extension)
    required: false
  add_timestamp_suffix:
    description:
      Set to 'true' to add a timestamp to the file name, 'false' to disable
    required: false
    default: 'true'

outputs:
  uploaded_file:
    description: The zip file or file uploaded

runs:
  using: docker
  image: Dockerfile
  env:
    UPLOAD_URL: ${{ inputs.upload_url }}
    UPLOAD_PATH: ${{ inputs.upload_path }}
    UPLOAD_NAME: ${{ inputs.upload_name }}
    ADD_TIMESTAMP_SUFFIX: ${{ inputs.add_timestamp_suffix }}

branding:
  icon: upload-cloud
  color: blue
