name: Znas Upload
description: |
  A GitHub Action that uploads a folder or file to Znas using Puppeteer via Docker.

inputs:
  upload_url:
    description: The URL to upload files to
    required: true
  upload_path:
    description: The path of the folder or file to upload
    required: true
  upload_name:
    description: The optional name for the uploaded zip file (without extension)
    required: false

outputs:
  uploaded_file:
    description: The zip file uploaded

runs:
  using: docker
  image: Dockerfile
  env:
    UPLOAD_URL: ${{ inputs.upload_url }}
    UPLOAD_PATH: ${{ inputs.upload_path }}
    UPLOAD_NAME: ${{ inputs.upload_name }}

branding:
  icon: upload-cloud
  color: blue
