
name: Znas Upload
description: A GitHub Action that uploads files to Znas link using Puppeteer via Docker.
inputs:
  upload_url:
    description: The URL to upload files to
    required: true
  upload_file:
    description: The path of the file to upload
    required: true
runs:
  using: docker
  image: Dockerfile
  env:
    UPLOAD_URL: ${{ inputs.upload_url }}
    UPLOAD_FILE: ${{ inputs.upload_file }}
